### ISSUE TITLE
Login (Remember Me ON)

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#664]
## Description 
Login functionality

## Steps to reproduce issue 
Slide [Remember Me] to ON
Enter Username, [Next] activates
Enter Password, [Previous] & [Go] activate
Login - Spideroak Logo will appear
Enter incorrect password: 3-5 sec error message, fields not cleared
Enter correct password: success

## Expected result 
Log Out returns a message saying "Are you sure you want to sign out?"
Log Out returns user to home login screen with username still in the username spot.

## Actual result 
Not showing me the Stay Logged In dialogue.

## Other information 
Reported by: Renee Jackson 

Test case number: TC04 

Test run: [http://spideroak.testlodge.com/projects/3096/runs/137336?tab=2&run_section_id=68049#executed_case_6977542](http://spideroak.testlodge.com/projects/3096/runs/137336?tab=2&run_section_id=68049#executed_case_6977542)

**Comment by kenmanheimer** [comment]
I'm totally perplexed by this report. (-:

1. It's hard to tell where you're starting from.
  * It could be the settings activity, where "Stay logged in" has a slider - but you can't actually enter a username and password there.
  * It could be the login page, but on the login page, the "Stay logged in" control is a checkbox, not a slider, as indicated.
  * However, the "Expected result" section of the report refers to Log Out returning the "Are you sure..." message - only the settings page has a logout.
  * So I'm beat, already. (I can often resolve a pretty good guess, even though I'll still ask because I want to push back against ambiguity to improve the communication process. This time I'm really unable to tell.)
2. You mention [Next], [Previous], and [Go] buttons activating.
  * I don't get [Next] or [Previous] on either iOS or Android, but I do get "<" and ">" next field and previous field arrows, when things are filled in, on iOS, and know that some Android devices have had Next and Previous. So I'm unable to tell which those are, but suspect it's iOS?
  * I can't tell if these details actually pertain to the problem, or are just for the sake of having all the details so an automated procedure could be concocted. I'm sympathetic to that, just trying to point out incidental details that are making finding the actual difficulty, difficult.
3. In the "Steps to reproduce" section of the report, you mention that fields are not cleared. *If* you're starting from the login screen, then we intend for only the password field to be cleared, all the rest should be preserved. I thought for a while that you were reporting that the Password field was not cleared (maybe because of the Next and Previous jockeying, or something), or that you were expecting the other fields to be cleared, but now suspect that's neither is the concern of the report.
4. Having "Actual result" be 'Not showing me the Stay Logged In dialogue." suggests to me that you're expecting the "Stay logged in dialog" to show every time you log in with "Stay logged in" set (though I'm genuinely still confused about being on the Login screen or the Setting screen).
  * In case this is it, the "Stay logged in" dialog is a one-time thing, per account. The purpose is to inform each user that "Stay logged in" stashes the credentials on the device, by notifying them until they accept it. If they do accept it, then they will not be warned again (on that device, unless the app is uninstalled and reinstalled, etc). If they do not accept it, then the login resumes, but "Stay logged in" is not maintained (as indicated on the settings page), and they will get the confirmation dialog again.
  * I'm leaning towards thinking that this concern is the reason for the issue, but genuinely unsure.

I suggest all this because I realize you're shaking out the process for reporting issues, from an external facility. I know that you're juggling a lot of concerns, including trying to be thorough and specific about the actions involved, trying to indicate different results possible, etc. You're concerned with audiences from various different roles, but in our particular role we need it clear what the specific problem is that's motivating the report.

**Comment by reneelynn** [comment]
So what TestLodge is apparently doing is just copying my test cases in and writing what I would normally put by itself in a bug report under the "actual results" The rest of it is just what's written in Testlodge as steps for QA staff to follow. Seems like either I need to just give up on @merickson's dream of integration or totally change how the tests are written.

**Comment by reneelynn** [comment]
Additionally, some of the language like [Go] and sliders vs checkboxes are anomalies left over from previous versions of the app or mockups that I apparently haven't quite scrubbed from our docs yet.

**Comment by reneelynn** [comment]
By the way this is showing the "Please Note" warning screen about staying logged in in Android, so this is iOS specific that I'm not seeing it.

**Comment by kenmanheimer** [comment]
Are you saying you're not seeing the "Please note" screen on iOS, ever? I'm seeing it on the very first time I try to log in with each account. (You may need to uninstall the app and reinstall it to ensure you're getting a very-first-time.)

**Comment by kenmanheimer** [comment]
@reneelynn can you confirm that you're not seeing it on the very first time stay-logged-in attempt for each account? I've been unable to replicate the behavior on any of my iOS devices.

**Comment by reneelynn** [comment]
I thought I had as I was using new accounts, but I just cleared everything out completely on my phone and tried again, and I got it this time so closing but keeping an eye out

**Comment by kenmanheimer** [comment]
Ok, definitely do keep alert for it - the warning keeps us honest re ZK. Thanks!
