### ISSUE TITLE
Pop-up keyboard after bypassing PIN

### ISSUE THREAD

**Issue by rebeccawatson** [SpiderOak/SpiderOakMobileClient#671]
This is weird. I haven't run into it before.

- log into account (Frog1/**********)
- set pin
- allow timeout, request for pin pops up
- bypass and logout
- full keyboard pops up on the homescreen/anywhere I try to navigate. I couldn't catch it in the screenshot, but there's a little blinking cursor on the orange screen... like I could just start typing over it? nothing happens when I tried to type.
- keyboard stays / split screen stays until I click done

![img_0371](https://cloud.githubusercontent.com/assets/5685302/6703958/cdd94ed4-ccff-11e4-8a57-694746c7b4ee.PNG)

![img_0372](https://cloud.githubusercontent.com/assets/5685302/6703963/d96dbc1c-ccff-11e4-8cfc-574e43c9420f.PNG)

**Comment by devgeeks** [comment]
Somehow, a text field has gotten focused that in *underneath* one of the other views.

Not sure if I'll be able to replicate, but might be able to be defensive and prevent it.

**Comment by devgeeks** [comment]
Right... after bypassing and getting to the login screen, did you hit the "X" to go to the initial screen while the keyboard was still up from being in the login or password input?

I can replicate that. I will make those fields blur when that "X" is hit.

**Comment by kenmanheimer** [comment]
Great catch, all!

@devgeeks insight works for me, too. No need to go through the PIN setting, etc, this is sufficient:

* Go to the login view.
* Select the Email/Username field - this activates the keyboard.
* Hit the 'x' button in the upper right
* This takes you to the preliminary view, with the cursor active where the (now hidden) Email/Username field is located, and the keyboard active.

The selected field will remain selected (on iOS, not Android). (In fact, you can login while still in that view! Type in a username, then tab or '>' Next to get to the password field, fill in the password, hit Enter or Go. It'll be dicey, because the preliminary view is still blocking the view. If you hit the "Log in ≫ " button, you'll see the logged in session.
