### ISSUE TITLE
404s on opening app

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#690]
internal support issue 589493

404 every time they open the app.

**Comment by reneelynn** [comment]
any luck parsing out what may be going on?

**Comment by kenmanheimer** [comment]
This is another case where the problem is very likely in the backend. The original ticket indicates that the user can't see their Hive contents in the web view, either.

(Unfortunately, the original ticket is in the old ticket system, and the clue about that is only contained in the new ticket's title. Unravelling that, hoping there would be salient info in the original, would have been  a lot simpler if a link to the original was included in the new ticket.  I can only imagine that each of us involved has to figure that out, and track it down, it would be good if we each reduced the next person's efforts by including a direct link - which I duly did in my griping comment, in the new internal issue.)

**Comment by reneelynn** [comment]
Thanks Ken - I don't have access to RT anymore so I can't track down those links. Any thoughts on what to tell user/ do I need to open a Trac ticket

**Comment by kenmanheimer** [comment]
I think some (object) server side investigation is going to be necessary, since the behavior happens with both web and mobile access.

(Seems like RT access is going to be necessary for you to wrangle tix, if the supporters are continuing to refer to old tickets there?)
