### ISSUE TITLE
French Translation "OK"

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/SpiderOakMobileClient#726]
Should be "d'accord" or, if abbreviation is desired, "d'acc"

This is seen on the "OK, I understand" dialogue for the ZK warning

**Comment by devgeeks** [comment]
OK

(haha, I amuse myself, anyway)

**Comment by devgeeks** [comment]
@kenmanheimer Can you ask mtwi about this? Is 'OK' in use in other French software translations?

**Comment by kenmanheimer** [comment]
Checking with MTWI.

**Comment by kenmanheimer** [comment]
Note that there are three fragments in our app that use "OK" (one being just the utterance, "OK"), and MTWI used "OK" in the French translation of each. It makes sense to have Warren weigh in on this, as well - @wpost?

**Comment by kenmanheimer** [comment]
Response from our translator:
> Je dirais OK, ou J'ai compris - parce que "d'accord" means OK, agreed more than 'Got it'.

I take that to indicate that "d'accord" signals acceptance of what a dialog conveys, rather than just understanding of it. On the other hand, looking around the web suggests strongly that "OK" is a common conventional element in French vocabulary, e.g. in:

* a [French stackexchange discussion](http://french.stackexchange.com/questions/6233/is-there-any-difference-between-daccord-and-okay-ok), and particularly [this discussion item](http://french.stackexchange.com/a/6235)
* and [this Yahoo answers entry](https://answers.yahoo.com/question/index?qid=20071203142534AAJhMcR)

there's plenty of evidence that OK is common colloquial French vocab.

Given all that, should we change the French translation?

**Comment by reneelynn** [comment]
As long as there's evidence that it's acceptable I'm good
